---
#
# Ansible managed
#
repository:
  description: Install and configure ansible on your system.
  homepage: https://buluma.github.io/
  topics: ansible, ansible, molecule, tox, playbook, hacktoberfest
