---
- name: Verify
  hosts: all
  become: false
  gather_facts: false

  tasks:
    - name: Check ansible is installed
      ansible.builtin.command:
        cmd: ansible --version
      changed_when: false
      register: ansible_check

    - name: Assert ansible is available
      ansible.builtin.assert:
        that: ansible_check.rc == 0
        fail_msg: "ansible command not available"
