---
#
# Ansible managed
#

name: "TODO 2 Issue"

on:
  push:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v3"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.6"
        id: "todo"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
